---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ci-metrics-sa
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::707767160287:role/ci-metrics-role-sa

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ci-metrics-role-sa
rules:
  - apiGroups: [""]
    resources:
      - namespaces
      - persistentvolumeclaims
      - secrets
      - pods
      - services
      - configmaps
      - serviceaccounts
    verbs:
      - get
      - list
      - describe
      - delete
      - update
      - watch

  - apiGroups: ["apps"]
    resources:
      - deployments
      - statefulsets
    verbs:
      - get
      - list
      - update
      - delete

  - apiGroups: ["batch"]
    resources:
      - jobs
      - cronjobs
    verbs:
      - get
      - list
      - update
      - delete

  - apiGroups: ["networking.k8s.io"]
    resources:
      - networkpolicies
      - ingresses
    verbs:
      - get
      - list
      - update
      - delete

  - apiGroups: ["external-secrets.io"]
    resources:
      - secretstores
      - externalsecrets
    verbs:
      - get
      - list
      - update
      - delete

  - apiGroups: ["rbac.authorization.k8s.io"]
    resources:
      - roles
      - rolebindings
      - clusterrolebindings
      - clusterroles
    verbs:
      - get
      - list
      - update
      - delete

  - apiGroups: ["policy"]
    resources:
      - poddisruptionbudgets
    verbs:
      - get
      - list
      - update
      - delete

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ci-metrics-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ci-metrics-role-sa
subjects:
  - kind: ServiceAccount
    name: helm-cleaner
    namespace: default
