apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ci-metrics-db
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: {{include "common.SecretStore" .}}
    kind: SecretStore
  target:
    name: ci-metrics-db
    creationPolicy: Owner
  data:
  - secretKey: METRICS_DB_DSN
    remoteRef:
      #name of secret in secrets manager
      key: {{include "ci-metrics-db" .}}
