apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    karpenter.sh/do-not-evict: "true"
  name: run-tes-tests
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: gen3job
    spec:
      # affinity:
      #   nodeAffinity:
      #     preferredDuringSchedulingIgnoredDuringExecution:
      #     - weight: 100
      #       preference:
      #         matchExpressions:
      #         - key: karpenter.sh/capacity-type
      #           operator: In
      #           values:
      #           - on-demand
      #     - weight: 99
      #       preference:
      #         matchExpressions:
      #         - key: eks.amazonaws.com/capacityType
      #           operator: In
      #           values:
      #           - ONDEMAND
      # volumes:
      # - name: creds-volume
      #   secret:
      #     secretName: "peregrine-creds"
      # - name: etl-mapping
      #   configMap:
      #     name: etl-mapping
      # - name: fence-yaml
      #   configMap:
      #     name: fence
      containers:
        - name: load-tests-tes
          # image: quay.io/cdis/containers:load-tests-tes
          image: quay.io/cdis/gen3-workflow:integration_tests_dicom_image
          imagePullPolicy: Always
          # ports:
          # - containerPort: 80
          # volumeMounts:
          #   - name: "creds-volume"
          #     readOnly: true
          #     mountPath: "/gen3/tube/creds.json"
          #     subPath: creds.json
          #   - name: "etl-mapping"
          #     readOnly: true
          #     mountPath: "/gen3/tube/etlMapping.yaml"
          #     subPath: "etlMapping.yaml"
          #   - name: "fence-yaml"
          #     readOnly: true
          #     mountPath: "/gen3/tube/user.yaml"
          #     subPath: user.yaml
          resources:
            limits:
              cpu: 2
              memory: 10Gi
            requests:
              cpu: 2
          command: ["/bin/bash"]
          args:
            - "-c"
            - |
              mkdir output
              if [[ "${TEST_SUITE}" == "ALL" ]]; then
                echo "Running full test suite..."
                poetry run pytest -s -n 1 -m "not wip" --alluredir allure-results --no-header --dist loadscope
              else
                echo "Running only: $TEST_SUITE"
                poetry run pytest -s -n 1 -m "not wip" --alluredir allure-results --no-header --dist loadscope -k "$TEST_SUITE"
              fi
              exitcode=$?
              echo "Exit code: $exitcode"
              exit "$exitcode"
      restartPolicy: Never
