apiVersion: v1
kind: ServiceAccount
metadata:
  name: run-tes-tests-sa
  namespace: ci-perf-tes
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::707767160287:role/github-action-role
---
apiVersion: batch/v1
kind: Job
metadata:
  name: run-tes-tests
  namespace: ci-perf-tes
  annotations:
    karpenter.sh/do-not-evict: "true"
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: gen3job
    spec:
      serviceAccountName: run-tes-tests-sa
      restartPolicy: Never
      volumes:
        - name: api-keys-volume
          secret:
            secretName: api-keys
      containers:
        - name: load-tests-tes
          image: quay.io/cdis/gen3-integration-tests:load_tests_tes-load-test-k8s
          # image: quay.io/cdis/gen3-integration-tests:load_tests_master
          # TODO revert to this ^
          imagePullPolicy: Always
          command: ["/bin/bash"]
          args:
            - "-c"
            - |
              mkdir output

              # Note: not using `pytest-xdist` (`-n` param) since we want to see live logs, and load
              # tests should be run one by one anyway
              if [[ "${TEST_SUITE}" == "ALL" ]]; then
                echo "Running full test suite..."
                poetry run pytest -s -m "not wip" --dist loadscope
              else
                echo "Running only: $TEST_SUITE"
                poetry run pytest -s -m "not wip" --dist loadscope -k "$TEST_SUITE"
              fi

              exitcode=$?
              echo "Exit code: $exitcode"

              echo "Uploading outputs to S3 bucket"
              aws s3 cp output s3://tes-load-tests-outputs/$(date "+%Y-%m-%d_%H:%M:%S") --recursive

              exit "$exitcode"
          volumeMounts:
            - name: api-keys-volume
              mountPath: /home/gen3/.gen3
          resources:
            limits:
              cpu: 2
              memory: 10Gi
            requests:
              cpu: 2
