apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    karpenter.sh/do-not-evict: "true"
  name: run-tes-tests
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: gen3job
    spec:
      # affinity:
      #   nodeAffinity:
      #     preferredDuringSchedulingIgnoredDuringExecution:
      #     - weight: 100
      #       preference:
      #         matchExpressions:
      #         - key: karpenter.sh/capacity-type
      #           operator: In
      #           values:
      #           - on-demand
      #     - weight: 99
      #       preference:
      #         matchExpressions:
      #         - key: eks.amazonaws.com/capacityType
      #           operator: In
      #           values:
      #           - ONDEMAND
      volumes:
        - name: api-keys-volume
          secret:
            secretName: api-keys
      containers:
        - name: load-tests-tes
          image: quay.io/cdis/gen3-integration-tests:load_tests_tes-load-test-k8s
          # image: quay.io/cdis/gen3-integration-tests:load_tests_master
          # TODO revert to this ^
          imagePullPolicy: Always
          # ports:
          # - containerPort: 80
          volumeMounts:
            - name: api-keys-volume
              mountPath: /home/gen3/.gen3
          resources:
            limits:
              cpu: 2
              memory: 10Gi
            requests:
              cpu: 2
          command: ["/bin/bash"]
          args:
            - "-c"
            - |
              mkdir output
              if [[ "${TEST_SUITE}" == "ALL" ]]; then
                echo "Running full test suite..."
                poetry run pytest -s -n 1 -m "not wip" --dist loadscope
              else
                echo "Running only: $TEST_SUITE"
                poetry run pytest -s -n 1 -m "not wip" --dist loadscope -k "$TEST_SUITE"
              fi
              exitcode=$?
              echo "Exit code: $exitcode"
              exit "$exitcode"
      restartPolicy: Never
