apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.secretStoreServiceAccount.name }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.secretStoreServiceAccount.roleArn }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: external-secrets-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: external-secrets-rolebinding
subjects:
- kind: ServiceAccount
  name: {{ .Values.secretStoreServiceAccount.name }}
roleRef:
  kind: Role
  name: external-secrets-role
  apiGroup: rbac.authorization.k8s.io
