image:
  repository: quay.io/cdis/ollama
  tag: chore_add_ollama_deployment
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 1
    memory: "4Gi"
  limits:
    cpu: 2
    memory: "6Gi"

service:
  type: ClusterIP
  port: 11434
