image:
  repository: quay.io/cdis/ollama
  tag: chore_add_kubectl_ai
  pullPolicy: IfNotPresent

pdb: true

resources:
  requests:
    cpu: 7
    memory: "12Gi"
  limits:
    cpu: 8
    memory: "14Gi"

service:
  type: ClusterIP
  port: 11434
