apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubectl-ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubectl-ai
  template:
    metadata:
      labels:
        app: kubectl-ai
    spec:
      serviceAccountName: kubectl-access-kubectl-ai
      containers:
        - name: kubectl-ai
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          ports:
            - containerPort: 80
          env:
            - name: OLLAMA_KEEP_ALIVE
              value: "-1"
            - name: KUBECTL_AI_TIMEOUT
              value: "300"
