apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubectl-access-ollama
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubectl-access-role-ollama
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/exec", "pods/log", "configmaps", "namespaces", "labels"]
    verbs: ["get", "list", "create", "patch"]
  - apiGroups: ["batch"]
    resources: ["cronjobs", "jobs"]
    verbs: ["get", "list", "create", "delete", "watch", "patch"]
  - apiGroups: ["apps"]
    resources: [deployments, deployments/scale]
    verbs: ["get", "list", "create", "delete", "watch", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubectl-access-binding-ollama
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubectl-access-role-ollama
subjects:
  - kind: ServiceAccount
    name: kubectl-access-ollama
    namespace: {{ .Release.Namespace }}
