# Note- Won't deploy via argocd in CI
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: gen3-ci
#   namespace: argocd
#   finalizers:
#   - resources-finalizer.argocd.argoproj.io
# spec:
#   project: default
#   sources:
#     - path: helm/gen3
#       repoURL: https://github.com/uc-cdis/gen3-helm
#       targetRevision: master
#       helm:
#         releaseName: oadc
#         valueFiles:
#           - $values/ci/values/values.yaml
#           - $values/ci/values/fence.yaml
#           - $values/ci/values/portal.yaml
#           - $values/ci/values/guppy.yaml
#           - $values/ci/values/etl.yaml
#     - repoURL: 'https://github.com/uc-cdis/gen3-gitops.git'
#       targetRevision: master
#       ref: values
#   destination:
#     server: "https://kubernetes.default.svc"
#     namespace: <>
#   syncPolicy:
#     syncOptions:
#     - CreateNamespace=true
#     automated:
#       selfHeal: true
