image:
  repository: quay.io/cdis/kubectl_ai
  tag: chore_add_kubectl_ai
  pullPolicy: Always

pdb: true

resources:
  requests:
    cpu: 2
    memory: "2Gi"
  limits:
    cpu: 4
    memory: "4Gi"

service:
  type: ClusterIP
  port: 11434

# Service account for accessing S3 bedrock access
serviceAccount:
  create: true
  name: s3-bedrock-access
  iamRoleArn: arn:aws:iam::707767160287:role/kubectl-ai-irsa
