name: Monthly Release

on:
  workflow_call:
    inputs:
      RELEASE_VERSION:
        required: true
        type: string
      LIST_OF_ENVIRONMENTS:
        required: true
        type: string
      TARGET_REPO_NAME:
        required: false
        type: string
        default: gen3-gitops
      WORKING_DIR:
        required: false
        type: string
        default: gen3-code-vigil/gen3-integration-tests

permissions:
  id-token: write
  contents: read
  pull-requests: write
  issues: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.repository.name }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
    integration_tests:
        runs-on: ubuntu-latest

        defaults:
          run:
            # the test directory in gen3-code-vigil
            working-directory: ${{ inputs.WORKING_DIR }}

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USERNAME: "PlanXCyborg"
          REPO: ${{ github.event.repository.name }}
          REPO_FN: ${{ github.event.repository.full_name }}
          BRANCH: ${{ github.event.pull_request.head.ref }}
          PR_NUM: ${{ github.event.pull_request.number }}
          COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
          RUN_NUM: ${{ github.run_number }}
          RUN_ID: ${{ github.run_id }}
          ATTEMPT_NUM: ${{ github.run_attempt }}
          GH_WORKSPACE: ${{ github.workspace }}
          RELEASE_VERSION: ${{ inputs.RELEASE_VERSION }}
          LIST_OF_ENVIRONMENTS: ${{ inputs.LIST_OF_ENVIRONMENTS }}
          TARGET_REPO_NAME: ${{ inputs.TARGET_REPO_NAME }}

        steps:
          # Ensure the PR is run under the same org as an Internal PR
          # and not by external forks/PRs
          - name: Check if PR is from the same organization
            if: ${{ github.repository_owner != 'uc-cdis' }}
            working-directory: ${{ github.workspace }}
            run:  |
              echo "github.repository_owner - ${{ github.repository_owner }}"
              echo "Skip pull requests from repositories not within the same organization"
              echo "SKIP_TESTS=true" >> $GITHUB_ENV

          - name: Checkout current repo
            if: ${{ env.SKIP_TESTS != 'true' }}
            uses: actions/checkout@v4

          - name: Split List of envs into folders
            run: |
              echo "FOLDERS=$(echo '${{ env.LIST_OF_ENVIRONMENTS }}' | tr ',' ' ')" >> $GITHUB_ENV

          - name: Loop through folders and create PRs
            env:
              GH_TOKEN: ${{ secrets.PLANXCYBORG_PAT }}
            run: |
              # Install dependencies
              pip install -U pip
              pip install poetry
              poetry install

              # Export needed variables
              export GEN3_GITOPS_PATH="$(pwd)/$TARGET_REPO_NAME"
              export GEN3_HELM_PATH="$(pwd)/gen3-helm"
              export TEST_REPO_PATH="$(pwd)"
              export THOR_REPO_LIST_PATH="$(pwd)/repo_list.txt"
              export GH_TOKEN=${GH_TOKEN//$'\n'/}

              # Clean up if already cloned
              rm -rf "$GEN3_GITOPS_PATH"

              # GH clone repositories and repo_list.txt file from Thor repo
              gh repo clone uc-cdis/gen3-gitops
              gh repo clone uc-cdis/gen3-helm
              gh api -H "Accept: application/vnd.github.v3.raw" /repos/uc-cdis/thor/contents/repo_list.txt > repo_list.txt

              for folder in $FOLDERS; do
                echo "Processing folder: $folder"
                cd $GEN3_GITOPS_PATH

                # Needed for committing or pushing changes
                git config --global user.name "PlanXCyborg"
                git config --global user.email "cdis@uchicago.edu"
                git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/uc-cdis/gen3-gitops.git

                # Set variables needed by $TEST_REPO_PATH/gen3_ci/scripts/deploy_monthly_release.py
                export TARGET_ENV=$folder
                TIMESTAMP=$(date +%s)
                PR_NAME="Gen3 Monthly Release ${RELEASE_VERSION} ${ENV} ${TIMESTAMP}"
                SANITIZED_ENV="${TARGET_ENV//\//_}"
                BRANCH_NAME="chore/apply_${RELEASE_VERSION}_to_${SANITIZED_ENV}_${TIMESTAMP}"
                COMMIT_MSG="Updating $TARGET_ENV with $RELEASE_VERSION"
                REPO_OWNER="uc-cdis"
                BASE_BRANCH="master"

                # PERFORM GIT OPERATIONS TO SWITCH TO NEW BRANCH and navigate to target env folder
                git switch master
                git fetch origin
                git checkout -b "$BRANCH_NAME"
                cd "${TARGET_ENV}/values/"

                # Update the yaml files
                poetry run python $TEST_REPO_PATH/gen3_ci/scripts/deploy_monthly_release.py

                # PUSH in the branch and create a PR
                git add .
                git commit -m "${COMMIT_MSG}"
                git config --global --list

                git push --set-upstream origin "$BRANCH_NAME"

                # Create a PR on $TARGET_REPO_NAME
                echo "Perform PR creation"
                gh pr create --title "$PR_NAME" --base "$BASE_BRANCH" --head "$BRANCH_NAME"
              done
