name: Load Test Metrics Image Build on Push

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "The tag to apply to this build. Defaults to 'latest'."
        default: "latest"
        required: false
  push:
    paths:
      - gen3-load-tests/gen3_ci/load_test_metrics/**

jobs:
  AmazonLinuxBase2023:
    name: Build Helm Cleanup Image
    uses: uc-cdis/.github/.github/workflows/image_build_push.yaml@master
    with:
      DOCKERFILE_LOCATION: "./gen3-load-tests/gen3_ci/load_test_metrics/Dockerfile"
      OVERRIDE_REPO_NAME: "load_test_metrics"
      OVERRIDE_TAG_NAME: "$(echo ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.tag || format('{0}', github.head_ref || github.ref_name) }} | tr / _)"
    secrets: inherit
