name: Quarantine / unquarantine CI Environment

on:
    workflow_dispatch:
        inputs:
            NAMESPACE:
                description: "CI environment to quarantine / unquarantine"
                required: true
            QUARANTINE:
                description: "Set `yes` to quarantine and `no` to unquarantine"
                required: true
                default: "yes"

permissions:
  id-token: write
  contents: read
  pull-requests: write
  issues: write

jobs:
    quarantine_ci_env:
        runs-on: ubuntu-latest
        env:
            NAMESPACE: ${{ inputs.NAMESPACE }}
            QUARANTINE: ${{ inputs.QURANTINE }}
            EKS_CLUSTER_NAME: ${{ secrets.EKS_CLUSTER_NAME }}
        steps:
          - name: Set up Python
            uses: actions/setup-python@v5
            with:
                python-version: '3.9'
          - name: Set up Go
            uses: actions/setup-go@v5
            with:
              go-version: '1.17'
          - name: Set Up kubectl
            uses: azure/setup-kubectl@v3
            with:
              version: latest
          - name: Configure AWS Credentials
            uses: aws-actions/configure-aws-credentials@v3
            with:
                role-to-assume: arn:aws:iam::707767160287:role/github-action-role
                role-session-name: GitHub_to_AWS_via_FederatedOIDC
                aws-region: "us-east-1"
                role-duration-seconds: 7200
          - name: Update kube config
            run: |
              aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER_NAME }} --region "us-east-1"
          - name: Quarantine namespace
            run: |
                if [[ "$QUARANTINE" == "yes" ]]; then
                  kubectl label namespace ${{ env.NAMESPACE }} quarantine=true --overwrite
                else
                  kubectl label namespace ${{ env.NAMESPACE }} quarantine=false --overwrite
                fi
