name: Test external PR

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Repository name (e.g. fence)'
        required: true
        type: string
      pr_number:
        description: 'Pull request number'
        required: true
        type: number

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  copy-external-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          repository: uc-cdis/${{ inputs.repo }}

      - name: Mirror external PR into internal copy
        run: |
          # Get PR metadata
          pr_json=$(gh pr view ${{ inputs.pr_number }} --repo uc-cdis/${{ inputs.repo }} \
            --json number,title,body,headRefName,headRepository,headRepositoryOwner,baseRefName)

          # Extract data
          head_ref=$(echo "$pr_json" | jq -r '.headRefName')
          head_repo=$(echo "$pr_json" | jq -r '.headRepository.cloneUrl')
          head_user=$(echo "$pr_json" | jq -r '.headRepositoryOwner.login')
          base_ref=$(echo "$pr_json" | jq -r '.baseRefName')
          title=$(echo "$pr_json" | jq -r '.title')
          body=$(echo "$pr_json" | jq -r '.body')
          branch="copy-of-external-pr-$pr_number"

          # Checkout base
          git fetch origin $base_ref && git checkout $base_ref

          # Fetch external PR branch and push to local
          git fetch "$head_repo" "$head_ref:$branch"
          git push origin "$branch"

          # Check if PR already exists
          existing_pr=$(gh pr list --head "$branch" --state open --json number -q '.[0].number')

          # Compose new PR title/body
          new_title="[Copy of external PR] $title"
          new_body="Copy of external PR #$pr_number from \`$head_user/${{ inputs.repo }}\`\n\nOriginal body:\n\n$body"

          if [[ -z "$existing_pr" ]]; then
            gh pr create --head "uc-cdis:$branch" --base "$base_ref" --title "$new_title" --body "$new_body"
            echo "✅ Created duplicate PR."
          else
            echo "ℹ️ Duplicate PR already exists (#$existing_pr)."
          fi
